chg: dev: use SSH instead of HTTPS
This is an attempt to remove stability

    error: RPC failed; HTTP 400 curl 92 HTTP/2 stream 7 was not closed cleanly: CANCEL (err 8)
    send-pack: unexpected disconnect while reading sideband packet
    fatal: the remote end hung up unexpectedly